"""Wire error codes declared by upstream x402 mechanisms.

GENERATED FILE — do not edit by hand. Regenerate with::

    python tools/sync_error_registry.py --upstream /path/to/x402

Why this is separate from ``SPEC_ERROR_REASONS``: that set is the legacy
``ErrorReasons`` Zod enum, which upstream froze under ``legacy/`` and stopped
extending. These are the codes current mechanisms declare and return directly.
``FA-ERR-001`` accepts the union, because a facilitator built on today's
packages returns codes from *both* halves and failing it for that would be our
bug, not its.

Extracted from 28 declaring files in the upstream tree; see
``tools/sync_error_registry.py`` for the declaration patterns and exclusions.
"""

from __future__ import annotations

#: Every wire error code declared outside the legacy `ErrorReasons` enum.
#: 344 codes from 28 files.
MECHANISM_ERROR_CODES = frozenset(
    {
        # go/errors.go
        "failed_to_marshal_payload",
        "failed_to_marshal_requirements",
        "insufficient_funds",
        "invalid_payment",
        "invalid_response",
        "invalid_v1_payload",
        "invalid_v1_requirements",
        "invalid_v2_payload",
        "invalid_v2_requirements",
        "invalid_version",
        "network_mismatch",
        "no_facilitator_for_network",
        "payment_expired",
        "payment_required",
        "scheme_mismatch",
        "settlement_failed",
        "signature_invalid",
        "unsupported_network",
        "unsupported_scheme",
        # go/extensions/signinwithx/types.go
        "invalid_siwx_chain_id",
        "invalid_siwx_domain_mismatch",
        "invalid_siwx_expiration_time",
        "invalid_siwx_expired",
        "invalid_siwx_issued_at",
        "invalid_siwx_issued_at_in_future",
        "invalid_siwx_issued_at_too_old",
        "invalid_siwx_malformed_signature",
        "invalid_siwx_nonce",
        "invalid_siwx_not_before",
        "invalid_siwx_not_yet_valid",
        "invalid_siwx_signature",
        "invalid_siwx_unsupported_chain",
        "invalid_siwx_uri_mismatch",
        "invalid_siwx_verifier_error",
        # go/mechanisms/evm/batch-settlement/errors.go
        "invalid_batch_settlement_evm_channel_busy",
        "invalid_batch_settlement_evm_channel_id_invalid",
        "invalid_batch_settlement_evm_channel_id_mismatch",
        "invalid_batch_settlement_evm_charge_exceeds_signed_cumulative",
        "invalid_batch_settlement_evm_cumulative_amount_mismatch",
        "invalid_batch_settlement_evm_cumulative_below_claimed",
        "invalid_batch_settlement_evm_missing_channel",
        "invalid_batch_settlement_evm_refund_amount_exceeds_balance",
        "invalid_batch_settlement_evm_refund_amount_invalid",
        "invalid_batch_settlement_evm_refund_no_balance",
        "invalid_batch_settlement_evm_verification_state_unavailable",
        # go/mechanisms/evm/batch-settlement/facilitator/errors.go
        "invalid_batch_settlement_evm_authorizer_address_mismatch",
        "invalid_batch_settlement_evm_authorizer_not_configured",
        "invalid_batch_settlement_evm_channel_not_found",
        "invalid_batch_settlement_evm_channel_state_read_failed",
        "invalid_batch_settlement_evm_claim_payload",
        "invalid_batch_settlement_evm_claim_simulation_failed",
        "invalid_batch_settlement_evm_claim_transaction_failed",
        "invalid_batch_settlement_evm_cumulative_exceeds_balance",
        "invalid_batch_settlement_evm_deposit_payload",
        "invalid_batch_settlement_evm_deposit_simulation_failed",
        "invalid_batch_settlement_evm_deposit_transaction_failed",
        "invalid_batch_settlement_evm_eip2612_amount_mismatch",
        "invalid_batch_settlement_evm_eip2612_asset_mismatch",
        "invalid_batch_settlement_evm_eip2612_deadline_expired",
        "invalid_batch_settlement_evm_eip2612_invalid_format",
        "invalid_batch_settlement_evm_eip2612_invalid_signature",
        "invalid_batch_settlement_evm_eip2612_owner_mismatch",
        "invalid_batch_settlement_evm_eip2612_spender_mismatch",
        "invalid_batch_settlement_evm_eip6492_factory_not_allowed",
        "invalid_batch_settlement_evm_erc20_approval_asset_mismatch",
        "invalid_batch_settlement_evm_erc20_approval_broadcast_failed",
        "invalid_batch_settlement_evm_erc20_approval_from_mismatch",
        "invalid_batch_settlement_evm_erc20_approval_invalid_format",
        "invalid_batch_settlement_evm_erc20_approval_unavailable",
        "invalid_batch_settlement_evm_erc20_approval_wrong_spender",
        "invalid_batch_settlement_evm_erc3009_authorization_required",
        "invalid_batch_settlement_evm_insufficient_balance",
        "invalid_batch_settlement_evm_missing_eip712_domain",
        "invalid_batch_settlement_evm_network_mismatch",
        "invalid_batch_settlement_evm_nothing_to_settle",
        "invalid_batch_settlement_evm_payload_authorization_valid_after",
        "invalid_batch_settlement_evm_payload_authorization_valid_before",
        "invalid_batch_settlement_evm_payload_type",
        "invalid_batch_settlement_evm_permit2_allowance_required",
        "invalid_batch_settlement_evm_permit2_amount_mismatch",
        "invalid_batch_settlement_evm_permit2_authorization_required",
        "invalid_batch_settlement_evm_permit2_deadline_expired",
        "invalid_batch_settlement_evm_permit2_invalid_signature",
        "invalid_batch_settlement_evm_permit2_invalid_spender",
        "invalid_batch_settlement_evm_receive_authorization_signature",
        "invalid_batch_settlement_evm_receiver_authorizer_mismatch",
        "invalid_batch_settlement_evm_receiver_mismatch",
        "invalid_batch_settlement_evm_refund_payload",
        "invalid_batch_settlement_evm_refund_simulation_failed",
        "invalid_batch_settlement_evm_refund_transaction_failed",
        "invalid_batch_settlement_evm_rpc_read_failed",
        "invalid_batch_settlement_evm_scheme",
        "invalid_batch_settlement_evm_settle_payload",
        "invalid_batch_settlement_evm_settle_simulation_failed",
        "invalid_batch_settlement_evm_settle_transaction_failed",
        "invalid_batch_settlement_evm_smart_wallet_deployment_failed",
        "invalid_batch_settlement_evm_token_mismatch",
        "invalid_batch_settlement_evm_transaction_reverted",
        "invalid_batch_settlement_evm_unknown_settle_action",
        "invalid_batch_settlement_evm_voucher_payload",
        "invalid_batch_settlement_evm_voucher_signature",
        "invalid_batch_settlement_evm_wait_for_receipt_failed",
        "invalid_batch_settlement_evm_withdraw_delay_mismatch",
        "invalid_batch_settlement_evm_withdraw_delay_out_of_range",
        # go/mechanisms/evm/constants.go
        "invalid_exact_evm_payload_undeployed_smart_wallet",
        # go/mechanisms/evm/exact/client/errors.go
        "invalid_exact_evm_client_amount",
        "invalid_exact_evm_client_failed_to_sign_authorization",
        "invalid_exact_evm_client_failed_to_sign_permit2_authorization",
        # go/mechanisms/evm/exact/facilitator/errors.go
        "eip6492_factory_not_allowed",
        "erc20_approval_asset_mismatch",
        "erc20_approval_from_mismatch",
        "erc20_approval_spender_not_permit2",
        "erc20_approval_tx_failed",
        "erc20_approval_tx_invalid_signature",
        "erc20_approval_tx_parse_failed",
        "erc20_approval_tx_signer_mismatch",
        "erc20_approval_tx_wrong_selector",
        "erc20_approval_tx_wrong_spender",
        "erc20_approval_tx_wrong_target",
        "invalid_erc20_approval_extension_format",
        "invalid_exact_evm_authorization_value",
        "invalid_exact_evm_eip3009_not_supported",
        "invalid_exact_evm_failed_to_check_deployment",
        "invalid_exact_evm_failed_to_check_nonce",
        "invalid_exact_evm_failed_to_execute_transfer",
        "invalid_exact_evm_failed_to_get_balance",
        "invalid_exact_evm_failed_to_get_network_config",
        "invalid_exact_evm_failed_to_get_receipt",
        "invalid_exact_evm_failed_to_parse_signature",
        "invalid_exact_evm_failed_to_verify_signature",
        "invalid_exact_evm_insufficient_balance",
        "invalid_exact_evm_missing_eip712_domain",
        "invalid_exact_evm_network_mismatch",
        "invalid_exact_evm_nonce_already_used",
        "invalid_exact_evm_payload",
        "invalid_exact_evm_payload_authorization_valid_after",
        "invalid_exact_evm_payload_authorization_valid_before",
        "invalid_exact_evm_payload_authorization_value_mismatch",
        "invalid_exact_evm_payload_missing_signature",
        "invalid_exact_evm_recipient_mismatch",
        "invalid_exact_evm_required_amount",
        "invalid_exact_evm_scheme",
        "invalid_exact_evm_signature",
        "invalid_exact_evm_signature_format",
        "invalid_exact_evm_token_name_mismatch",
        "invalid_exact_evm_token_version_mismatch",
        "invalid_exact_evm_transaction_failed",
        "invalid_exact_evm_transaction_simulation_failed",
        "invalid_exact_evm_transfer_event_mismatch",
        "invalid_exact_evm_verification_failed",
        "smart_wallet_deployment_failed",
        "unsupported_payload_type",
        # go/mechanisms/evm/exact/server/errors.go
        "invalid_exact_evm_server_amount_must_be_string",
        "invalid_exact_evm_server_amount_required",
        "invalid_exact_evm_server_asset_address_required",
        "invalid_exact_evm_server_failed_to_convert_amount",
        "invalid_exact_evm_server_failed_to_parse_amount",
        "invalid_exact_evm_server_failed_to_parse_price",
        "invalid_exact_evm_server_invalid_amount",
        "invalid_exact_evm_server_invalid_asset",
        "invalid_exact_evm_server_invalid_payto_address",
        "invalid_exact_evm_server_invalid_token_amount",
        "invalid_exact_evm_server_no_asset_specified",
        "invalid_exact_evm_server_unsupported_price_type",
        # go/mechanisms/evm/exact/v1/facilitator/errors.go
        "invalid_exact_evm_extra_field",
        "invalid_exact_evm_insufficient_funds",
        "invalid_exact_evm_payload_authorization_value",
        "invalid_exact_evm_payload_recipient_mismatch",
        "invalid_exact_evm_payload_signature",
        "invalid_exact_evm_transaction_state",
        "invalid_exact_evm_unsupported_scheme",
        # go/mechanisms/evm/permit2_errors.go
        "asset_not_deployed_contract",
        "erc20_approval_broadcast_failed",
        "erc20_approval_insufficient_eth_for_gas",
        "invalid_permit2_recipient_mismatch",
        "invalid_permit2_signature",
        "invalid_permit2_spender",
        "permit2_2612_amount_mismatch",
        "permit2_allowance_required",
        "permit2_amount_mismatch",
        "permit2_deadline_expired",
        "permit2_insufficient_balance",
        "permit2_invalid_amount",
        "permit2_invalid_destination",
        "permit2_invalid_nonce",
        "permit2_invalid_owner",
        "permit2_not_yet_valid",
        "permit2_payment_too_early",
        "permit2_proxy_not_deployed",
        "permit2_simulation_failed",
        "permit2_token_mismatch",
        # go/mechanisms/evm/upto/client/errors.go
        "invalid_upto_evm_client_amount",
        "invalid_upto_evm_client_failed_to_sign_permit2_authorization",
        "invalid_upto_evm_client_missing_facilitator_address",
        # go/mechanisms/evm/upto/facilitator/errors.go
        "invalid_upto_evm_failed_to_get_network_config",
        "invalid_upto_evm_failed_to_get_receipt",
        "invalid_upto_evm_network_mismatch",
        "invalid_upto_evm_payload",
        "invalid_upto_evm_payload_settlement_exceeds_amount",
        "invalid_upto_evm_required_amount",
        "invalid_upto_evm_scheme",
        "invalid_upto_evm_signature_format",
        "invalid_upto_evm_transaction_failed",
        "invalid_upto_evm_verification_failed",
        "upto_amount_exceeds_permitted",
        "upto_facilitator_mismatch",
        "upto_unauthorized_facilitator",
        # go/mechanisms/evm/upto/server/errors.go
        "invalid_upto_evm_server_amount_must_be_string",
        "invalid_upto_evm_server_amount_required",
        "invalid_upto_evm_server_asset_address_required",
        "invalid_upto_evm_server_failed_to_convert_amount",
        "invalid_upto_evm_server_failed_to_parse_amount",
        "invalid_upto_evm_server_failed_to_parse_price",
        "invalid_upto_evm_server_invalid_amount",
        "invalid_upto_evm_server_invalid_asset",
        "invalid_upto_evm_server_invalid_payto_address",
        "invalid_upto_evm_server_invalid_token_amount",
        "invalid_upto_evm_server_no_asset_specified",
        "invalid_upto_evm_server_unsupported_price_type",
        # go/mechanisms/svm/exact/client/errors.go
        "invalid_exact_solana_client_failed_to_build_compute_limit_instruction",
        "invalid_exact_solana_client_failed_to_build_compute_price_instruction",
        "invalid_exact_solana_client_failed_to_build_memo_instruction",
        "invalid_exact_solana_client_failed_to_build_transfer_instruction",
        "invalid_exact_solana_client_failed_to_create_transaction",
        "invalid_exact_solana_client_failed_to_decode_mint_data",
        "invalid_exact_solana_client_failed_to_derive_destination_ata",
        "invalid_exact_solana_client_failed_to_derive_source_ata",
        "invalid_exact_solana_client_failed_to_encode_transaction",
        "invalid_exact_solana_client_failed_to_get_latest_blockhash",
        "invalid_exact_solana_client_failed_to_get_mint_account",
        "invalid_exact_solana_client_failed_to_sign_transaction",
        "invalid_exact_solana_client_fee_payer_required",
        "invalid_exact_solana_client_invalid_amount",
        "invalid_exact_solana_client_invalid_asset_address",
        "invalid_exact_solana_client_invalid_fee_payer_address",
        "invalid_exact_solana_client_invalid_payto_address",
        "invalid_exact_solana_client_memo_exceeds_max_size",
        "invalid_exact_solana_client_unknown_token_program",
        "invalid_exact_solana_client_unsupported_network",
        # go/mechanisms/svm/exact/facilitator/errors.go
        "duplicate_settlement",
        "invalid_exact_solana_fee_payer_mismatch",
        "invalid_exact_solana_fee_payer_not_managed_by_facilitator",
        "invalid_exact_solana_invalid_fee_payer",
        "invalid_exact_solana_network_mismatch",
        "invalid_exact_solana_payload_amount_insufficient",
        "invalid_exact_solana_payload_memo_count",
        "invalid_exact_solana_payload_memo_mismatch",
        "invalid_exact_solana_payload_mint_mismatch",
        "invalid_exact_solana_payload_missing_fee_payer",
        "invalid_exact_solana_payload_no_transfer_instruction",
        "invalid_exact_solana_payload_recipient_mismatch",
        "invalid_exact_solana_payload_transaction",
        "invalid_exact_solana_payload_transaction_could_not_be_decoded",
        "invalid_exact_solana_payload_transaction_fee_payer_transferring_funds",
        "invalid_exact_solana_payload_transaction_instructions_compute_limit_instruction",
        "invalid_exact_solana_payload_transaction_instructions_compute_price_instruction",
        "invalid_exact_solana_payload_transaction_instructions_compute_price_instruction_too_high",
        "invalid_exact_solana_payload_transaction_instructions_length",
        "invalid_exact_solana_payload_unknown_fifth_instruction",
        "invalid_exact_solana_payload_unknown_fourth_instruction",
        "invalid_exact_solana_payload_unknown_sixth_instruction",
        "invalid_exact_solana_transaction_confirmation_failed",
        "invalid_exact_solana_transaction_failed",
        "invalid_exact_solana_transaction_signing_failed",
        "invalid_exact_solana_transaction_simulation_failed",
        "invalid_exact_solana_unsupported_scheme",
        "invalid_exact_solana_verification_failed",
        # go/mechanisms/svm/exact/server/errors.go
        "invalid_exact_solana_server_amount_must_be_string",
        "invalid_exact_solana_server_failed_to_convert_amount",
        "invalid_exact_solana_server_failed_to_parse_amount",
        "invalid_exact_solana_server_failed_to_parse_price",
        "invalid_exact_solana_server_invalid_price_format",
        # go/mechanisms/svm/exact/v1/client/errors.go
        "invalid_exact_solana_client_invalid_extra_field",
        # go/mechanisms/svm/exact/v1/facilitator/errors.go
        "invalid_exact_solana_extra_field",
        # python/x402/mechanisms/evm/constants.py
        "invalid_exact_evm_failed_to_get_asset_info",
        "missing_eip712_domain",
        "transaction_failed",
        # python/x402/mechanisms/svm/constants.py
        "fee_payer_not_managed_by_facilitator",
        "invalid_exact_svm_payload",
        "invalid_exact_svm_payload_amount_insufficient",
        "invalid_exact_svm_payload_memo_count",
        "invalid_exact_svm_payload_memo_mismatch",
        "invalid_exact_svm_payload_mint_mismatch",
        "invalid_exact_svm_payload_missing_fee_payer",
        "invalid_exact_svm_payload_no_transfer_instruction",
        "invalid_exact_svm_payload_recipient_mismatch",
        "invalid_exact_svm_payload_transaction_could_not_be_decoded",
        "invalid_exact_svm_payload_transaction_fee_payer_transferring_funds",
        "invalid_exact_svm_payload_transaction_instructions_length",
        "invalid_exact_svm_payload_unknown_fifth_instruction",
        "invalid_exact_svm_payload_unknown_fourth_instruction",
        "invalid_exact_svm_payload_unknown_sixth_instruction",
        "transaction_simulation_failed",
        # python/x402/mechanisms/tvm/constants.py
        "account_frozen",
        "facilitator_insufficient_balance",
        "insufficient_balance",
        "invalid_exact_tvm_payload",
        "invalid_exact_tvm_payload_amount_mismatch",
        "invalid_exact_tvm_payload_asset_mismatch",
        "invalid_exact_tvm_payload_attached_ton_amount_too_high",
        "invalid_exact_tvm_payload_extensions_dict_mismatch",
        "invalid_exact_tvm_payload_invalid_code_hash",
        "invalid_exact_tvm_payload_invalid_signature",
        "invalid_exact_tvm_payload_jetton_transfer",
        "invalid_exact_tvm_payload_recipient_mismatch",
        "invalid_exact_tvm_payload_seqno_mismatch",
        "invalid_exact_tvm_payload_settlement_boc",
        "invalid_exact_tvm_payload_signature_mode_mismatch",
        "invalid_exact_tvm_payload_valid_until_expired",
        "invalid_exact_tvm_payload_valid_until_too_far",
        "invalid_exact_tvm_payload_w5_actions",
        "invalid_exact_tvm_payload_w5_internal_signed_request",
        "invalid_exact_tvm_payload_wallet_id_mismatch",
        "simulation_failed",
        "unsupported_version",
        # python/x402/server_base.py
        "extension_echo_mismatch",
        # typescript/packages/mechanisms/avm/src/exact/facilitator/errors.ts
        "invalid_exact_avm_amount_mismatch",
        "invalid_exact_avm_asset_mismatch",
        "invalid_exact_avm_confirmation_failed",
        "invalid_exact_avm_facilitator_transferring",
        "invalid_exact_avm_fee_too_high",
        "invalid_exact_avm_group_size_exceeded",
        "invalid_exact_avm_invalid_fee_payer",
        "invalid_exact_avm_invalid_group_id",
        "invalid_exact_avm_invalid_signature",
        "invalid_exact_avm_invalid_transaction",
        "invalid_exact_avm_invalid_version",
        "invalid_exact_avm_network_mismatch",
        "invalid_exact_avm_not_asset_transfer",
        "invalid_exact_avm_payload",
        "invalid_exact_avm_payment_index",
        "invalid_exact_avm_payment_not_signed",
        "invalid_exact_avm_receiver_mismatch",
        "invalid_exact_avm_scheme",
        "invalid_exact_avm_settlement_failed",
        "invalid_exact_avm_simulation_failed",
        "invalid_exact_avm_unsigned_non_facilitator",
        # typescript/packages/mechanisms/evm/src/exact/facilitator/errors.ts
        "eip2612_asset_mismatch",
        "eip2612_deadline_expired",
        "eip2612_from_mismatch",
        "eip2612_spender_not_permit2",
        "erc20_approval_tx_invalid_calldata",
        "invalid_eip2612_extension_format",
        "invalid_transaction_state",
    }
)
